import type {
  PlanetName,
} from "../contracts/facts";

import type {
  CapabilityCategory,
} from "./types";

export type CapabilityDefinition = {
  key: string;
  label: string;
  description: string;

  category: CapabilityCategory;

  primaryPlanets: PlanetName[];
  supportingPlanets: PlanetName[];

  themeKeys: string[];
  influenceThemeKeys: string[];
  limitationKeys: string[];

  baseWeight: number;
};

export const CAPABILITY_DEFINITIONS: CapabilityDefinition[] = [
  {
    key: "knowledge",
    label: "Knowledge",
    description:
      "Capacity to acquire, retain, organise, explain, and apply knowledge.",
    category: "cognitive",
    primaryPlanets: [
      "Mercury",
      "Jupiter",
    ],
    supportingPlanets: [
      "Moon",
      "Ketu",
    ],
    themeKeys: [
      "knowledge",
      "knowledge_synthesis",
      "teaching",
      "guidance",
      "publishing",
      "learning",
      "education",
      "philosophy",
      "consulting",
    ],
    influenceThemeKeys: [
      "knowledge",
      "teaching",
      "publishing",
      "consulting",
      "guidance",
    ],
    limitationKeys: [
      "overconfidence_in_knowledge",
      "excessive_theorising",
      "overgeneralisation",
      "dogmatism",
    ],
    baseWeight: 10,
  },
  {
    key: "analysis",
    label: "Analysis",
    description:
      "Capacity to break down information, compare factors, diagnose patterns, and reach reasoned conclusions.",
    category: "cognitive",
    primaryPlanets: [
      "Mercury",
      "Ketu",
    ],
    supportingPlanets: [
      "Saturn",
      "Jupiter",
    ],
    themeKeys: [
      "analysis",
      "analytics",
      "diagnosis",
      "diagnostics",
      "problem_diagnosis",
      "audit",
      "research",
      "pattern_recognition",
      "technical_mastery",
    ],
    influenceThemeKeys: [
      "research",
      "diagnostics",
      "coding",
      "symbolic_analysis",
      "strategy",
    ],
    limitationKeys: [
      "overanalysis",
      "fear_of_mistakes",
      "slow_decision_making",
      "excessive_theorising",
    ],
    baseWeight: 10,
  },
  {
    key: "learning",
    label: "Learning",
    description:
      "Capacity to absorb new information, adapt intellectually, and develop skills over time.",
    category: "cognitive",
    primaryPlanets: [
      "Mercury",
      "Moon",
    ],
    supportingPlanets: [
      "Jupiter",
      "Rahu",
    ],
    themeKeys: [
      "learning",
      "rapid_learning",
      "memory",
      "curiosity",
      "education",
      "communication",
      "adaptability",
      "teaching",
    ],
    influenceThemeKeys: [
      "knowledge",
      "communication",
      "education",
      "technology",
    ],
    limitationKeys: [
      "restlessness",
      "scattered_thinking",
      "overthinking",
      "mental_heaviness",
    ],
    baseWeight: 8,
  },
  {
    key: "research",
    label: "Research",
    description:
      "Capacity for deep inquiry, hidden-pattern discovery, investigation, and specialist knowledge.",
    category: "cognitive",
    primaryPlanets: [
      "Ketu",
      "Mercury",
    ],
    supportingPlanets: [
      "Jupiter",
      "Saturn",
      "Rahu",
    ],
    themeKeys: [
      "research",
      "investigation",
      "diagnosis",
      "diagnostics",
      "occult_knowledge",
      "technical_research",
      "hidden_systems",
      "niche_expertise",
      "astrology",
    ],
    influenceThemeKeys: [
      "research",
      "diagnostics",
      "symbolic_analysis",
      "occult_knowledge",
      "hidden_systems",
    ],
    limitationKeys: [
      "withdrawal",
      "secrecy",
      "difficulty_explaining_insight",
      "extreme_withdrawal",
    ],
    baseWeight: 10,
  },
  {
    key: "innovation",
    label: "Innovation",
    description:
      "Capacity to combine ideas in unconventional ways and create new systems, tools, or approaches.",
    category: "cognitive",
    primaryPlanets: [
      "Rahu",
      "Mercury",
    ],
    supportingPlanets: [
      "Ketu",
      "Mars",
      "Saturn",
    ],
    themeKeys: [
      "innovation",
      "technology",
      "software",
      "ai",
      "digital_platforms",
      "coding",
      "systems_thinking",
      "disruption",
      "rapid_learning",
    ],
    influenceThemeKeys: [
      "technology",
      "ai",
      "digital_platforms",
      "coding",
      "disruption",
    ],
    limitationKeys: [
      "instability",
      "overreach",
      "recklessness",
      "obsession",
    ],
    baseWeight: 10,
  },
  {
    key: "strategic_thinking",
    label: "Strategic Thinking",
    description:
      "Capacity to see the wider pattern, prioritise, sequence action, and anticipate consequences.",
    category: "cognitive",
    primaryPlanets: [
      "Mercury",
      "Jupiter",
      "Sun",
    ],
    supportingPlanets: [
      "Saturn",
      "Rahu",
    ],
    themeKeys: [
      "strategy",
      "strategic_analysis",
      "business_strategy",
      "policy",
      "governance",
      "systems_thinking",
      "planning",
      "judgement",
    ],
    influenceThemeKeys: [
      "strategy",
      "policy",
      "governance",
      "knowledge",
    ],
    limitationKeys: [
      "overgeneralisation",
      "rigidity",
      "slow_decision_making",
      "overconfidence_in_beliefs",
    ],
    baseWeight: 10,
  },
  {
    key: "leadership",
    label: "Leadership",
    description:
      "Capacity to direct, influence, inspire, and carry responsibility for outcomes.",
    category: "leadership",
    primaryPlanets: [
      "Sun",
      "Jupiter",
      "Mars",
    ],
    supportingPlanets: [
      "Saturn",
      "Moon",
    ],
    themeKeys: [
      "leadership",
      "authority",
      "management",
      "guidance",
      "command",
      "executive_responsibility",
      "administration",
      "decision_making",
    ],
    influenceThemeKeys: [
      "leadership",
      "authority",
      "guidance",
      "command",
      "policy",
    ],
    limitationKeys: [
      "pride",
      "domination",
      "authority_conflict",
      "recognition_insecurity",
    ],
    baseWeight: 10,
  },
  {
    key: "authority",
    label: "Authority",
    description:
      "Capacity to hold status, make binding decisions, represent institutions, and command respect.",
    category: "leadership",
    primaryPlanets: [
      "Sun",
      "Saturn",
    ],
    supportingPlanets: [
      "Jupiter",
      "Mars",
    ],
    themeKeys: [
      "authority",
      "governance",
      "administration",
      "status",
      "policy",
      "institutions",
      "management",
      "responsibility",
    ],
    influenceThemeKeys: [
      "authority",
      "responsibility",
      "governance",
      "policy",
    ],
    limitationKeys: [
      "authority_conflict",
      "fear_of_recognition",
      "rigidity",
      "domination",
    ],
    baseWeight: 9,
  },
  {
    key: "decision_making",
    label: "Decision Making",
    description:
      "Capacity to assess choices, commit, and act with appropriate speed and judgement.",
    category: "leadership",
    primaryPlanets: [
      "Sun",
      "Mars",
      "Mercury",
    ],
    supportingPlanets: [
      "Jupiter",
      "Saturn",
    ],
    themeKeys: [
      "decision_making",
      "judgement",
      "strategy",
      "initiative",
      "command",
      "analysis",
      "problem_solving",
    ],
    influenceThemeKeys: [
      "strategy",
      "leadership",
      "command",
      "analysis",
    ],
    limitationKeys: [
      "slow_decision_making",
      "fear_of_mistakes",
      "impatience",
      "indecision",
    ],
    baseWeight: 9,
  },
  {
    key: "responsibility",
    label: "Responsibility",
    description:
      "Capacity to accept duty, remain accountable, and sustain commitments.",
    category: "leadership",
    primaryPlanets: [
      "Saturn",
      "Sun",
    ],
    supportingPlanets: [
      "Jupiter",
      "Moon",
    ],
    themeKeys: [
      "responsibility",
      "discipline",
      "governance",
      "administration",
      "service",
      "endurance",
      "mature_judgement",
    ],
    influenceThemeKeys: [
      "responsibility",
      "governance",
      "endurance",
      "discipline",
    ],
    limitationKeys: [
      "harsh_self_discipline",
      "delay",
      "pessimism",
      "fear_of_scarcity",
    ],
    baseWeight: 9,
  },
  {
    key: "governance",
    label: "Governance",
    description:
      "Capacity to create rules, manage institutions, control risk, and maintain standards.",
    category: "leadership",
    primaryPlanets: [
      "Saturn",
      "Sun",
      "Jupiter",
    ],
    supportingPlanets: [
      "Mercury",
      "Mars",
    ],
    themeKeys: [
      "governance",
      "compliance",
      "policy",
      "administration",
      "institutions",
      "audit",
      "justice",
      "management",
    ],
    influenceThemeKeys: [
      "governance",
      "policy",
      "law",
      "ethics",
      "responsibility",
    ],
    limitationKeys: [
      "rigidity",
      "over_control",
      "authority_conflict",
      "delay",
    ],
    baseWeight: 10,
  },
  {
    key: "execution",
    label: "Execution",
    description:
      "Capacity to convert intention into practical action and completed outcomes.",
    category: "execution",
    primaryPlanets: [
      "Mars",
      "Saturn",
    ],
    supportingPlanets: [
      "Sun",
      "Mercury",
    ],
    themeKeys: [
      "execution",
      "initiative",
      "operations",
      "engineering",
      "construction",
      "manufacturing",
      "problem_solving",
      "technical_mastery",
    ],
    influenceThemeKeys: [
      "engineering",
      "operations",
      "construction",
      "endurance",
      "command",
    ],
    limitationKeys: [
      "blocked_action",
      "frustration",
      "delay",
      "impatience",
    ],
    baseWeight: 10,
  },
  {
    key: "discipline",
    label: "Discipline",
    description:
      "Capacity to follow structure, persist through difficulty, and regulate effort.",
    category: "execution",
    primaryPlanets: [
      "Saturn",
      "Mars",
    ],
    supportingPlanets: [
      "Sun",
      "Ketu",
    ],
    themeKeys: [
      "discipline",
      "endurance",
      "responsibility",
      "persistent_problem_solving",
      "professional_discipline",
      "austerity",
      "service",
    ],
    influenceThemeKeys: [
      "discipline",
      "endurance",
      "responsibility",
      "austerity",
    ],
    limitationKeys: [
      "harsh_self_discipline",
      "frustration",
      "blocked_action",
      "pessimism",
    ],
    baseWeight: 9,
  },
  {
    key: "endurance",
    label: "Endurance",
    description:
      "Capacity to sustain effort, tolerate delay, and continue under pressure.",
    category: "execution",
    primaryPlanets: [
      "Saturn",
      "Mars",
    ],
    supportingPlanets: [
      "Moon",
      "Sun",
    ],
    themeKeys: [
      "endurance",
      "responsibility",
      "structured_growth",
      "persistent_problem_solving",
      "heavy_operations",
      "karmic_endurance",
    ],
    influenceThemeKeys: [
      "endurance",
      "responsibility",
      "operations",
    ],
    limitationKeys: [
      "frustration",
      "delay",
      "mental_heaviness",
      "burnout",
    ],
    baseWeight: 9,
  },
  {
    key: "operations",
    label: "Operations",
    description:
      "Capacity to organise people, processes, resources, logistics, and repeatable delivery.",
    category: "execution",
    primaryPlanets: [
      "Saturn",
      "Mars",
      "Mercury",
    ],
    supportingPlanets: [
      "Sun",
      "Rahu",
    ],
    themeKeys: [
      "operations",
      "process_design",
      "manufacturing",
      "logistics",
      "infrastructure",
      "compliance",
      "systems",
      "administration",
    ],
    influenceThemeKeys: [
      "operations",
      "engineering",
      "construction",
      "compliance",
      "large_systems",
    ],
    limitationKeys: [
      "blocked_action",
      "delay",
      "rigidity",
      "over_control",
    ],
    baseWeight: 10,
  },
  {
    key: "initiative",
    label: "Initiative",
    description:
      "Capacity to begin, take ownership, create momentum, and act independently.",
    category: "execution",
    primaryPlanets: [
      "Mars",
      "Sun",
    ],
    supportingPlanets: [
      "Rahu",
      "Mercury",
    ],
    themeKeys: [
      "initiative",
      "enterprise",
      "entrepreneurship",
      "self_made_effort",
      "courage",
      "independent_action",
      "competition",
    ],
    influenceThemeKeys: [
      "initiative",
      "command",
      "competition",
      "rapid_expansion",
    ],
    limitationKeys: [
      "impatience",
      "recklessness",
      "conflict",
      "blocked_action",
    ],
    baseWeight: 9,
  },
  {
    key: "commerce",
    label: "Commerce",
    description:
      "Capacity to identify value, exchange products or services, and understand markets.",
    category: "commercial",
    primaryPlanets: [
      "Mercury",
      "Venus",
    ],
    supportingPlanets: [
      "Moon",
      "Rahu",
      "Jupiter",
    ],
    themeKeys: [
      "commerce",
      "trade",
      "business_strategy",
      "knowledge_monetisation",
      "market_appeal",
      "customer_appeal",
      "negotiation",
      "sales",
    ],
    influenceThemeKeys: [
      "commerce",
      "branding",
      "marketing",
      "client_experience",
      "foreign_markets",
    ],
    limitationKeys: [
      "overconfidence_in_knowledge",
      "instability",
      "indulgence",
      "over_spending",
    ],
    baseWeight: 10,
  },
  {
    key: "sales",
    label: "Sales",
    description:
      "Capacity to persuade, pursue opportunities, overcome resistance, and close value exchanges.",
    category: "commercial",
    primaryPlanets: [
      "Mars",
      "Mercury",
    ],
    supportingPlanets: [
      "Venus",
      "Rahu",
      "Sun",
    ],
    themeKeys: [
      "sales",
      "communication_led_profession",
      "negotiation",
      "enterprise",
      "initiative",
      "customer_appeal",
      "market_appeal",
    ],
    influenceThemeKeys: [
      "commerce",
      "branding",
      "client_experience",
      "competition",
    ],
    limitationKeys: [
      "impatience",
      "domination",
      "inflated_promises",
      "recklessness",
    ],
    baseWeight: 9,
  },
  {
    key: "negotiation",
    label: "Negotiation",
    description:
      "Capacity to balance interests, communicate value, resolve differences, and reach workable agreements.",
    category: "commercial",
    primaryPlanets: [
      "Mercury",
      "Venus",
    ],
    supportingPlanets: [
      "Moon",
      "Jupiter",
      "Saturn",
    ],
    themeKeys: [
      "negotiation",
      "diplomacy",
      "consulting",
      "communication",
      "partnership_structures",
      "client_experience",
      "relationships",
    ],
    influenceThemeKeys: [
      "commerce",
      "client_experience",
      "relationships",
      "guidance",
    ],
    limitationKeys: [
      "indecision",
      "approval_dependence",
      "rigidity",
      "conflict",
    ],
    baseWeight: 9,
  },
  {
    key: "entrepreneurship",
    label: "Entrepreneurship",
    description:
      "Capacity to initiate ventures, assume calculated risk, create value, and build independent systems.",
    category: "commercial",
    primaryPlanets: [
      "Mars",
      "Mercury",
      "Rahu",
    ],
    supportingPlanets: [
      "Sun",
      "Jupiter",
      "Saturn",
      "Venus",
    ],
    themeKeys: [
      "entrepreneurship",
      "enterprise",
      "self_made_effort",
      "business_strategy",
      "risk_appetite",
      "foreign_markets",
      "digital_platforms",
      "sales",
    ],
    influenceThemeKeys: [
      "technology",
      "foreign_markets",
      "commerce",
      "rapid_expansion",
      "strategy",
    ],
    limitationKeys: [
      "recklessness",
      "instability",
      "overreach",
      "fear_of_loss",
    ],
    baseWeight: 10,
  },
  {
    key: "scale",
    label: "Scale",
    description:
      "Capacity to expand reach, manage larger systems, and multiply impact across markets or networks.",
    category: "commercial",
    primaryPlanets: [
      "Rahu",
      "Saturn",
      "Jupiter",
    ],
    supportingPlanets: [
      "Mercury",
      "Sun",
    ],
    themeKeys: [
      "scale",
      "foreign_markets",
      "digital_platforms",
      "network_gains",
      "mass_attraction",
      "large_systems",
      "technology",
      "publishing",
      "institutional_services",
    ],
    influenceThemeKeys: [
      "foreign_markets",
      "mass_influence",
      "technology",
      "large_systems",
      "media",
    ],
    limitationKeys: [
      "overreach",
      "instability",
      "control_obsession",
      "ethical_compromise",
    ],
    baseWeight: 10,
  },
  {
    key: "customer_understanding",
    label: "Customer Understanding",
    description:
      "Capacity to understand needs, trust, behaviour, emotion, and perceived value.",
    category: "commercial",
    primaryPlanets: [
      "Moon",
      "Venus",
      "Mercury",
    ],
    supportingPlanets: [
      "Rahu",
      "Jupiter",
    ],
    themeKeys: [
      "customer_understanding",
      "customer_appeal",
      "public_trust",
      "hospitality",
      "consumer_behaviour",
      "client_experience",
      "market_appeal",
      "emotional_appeal",
    ],
    influenceThemeKeys: [
      "customer_understanding",
      "public_appeal",
      "client_experience",
      "branding",
    ],
    limitationKeys: [
      "approval_dependence",
      "emotional_reactivity",
      "instability",
      "indulgence",
    ],
    baseWeight: 10,
  },
  {
    key: "creativity",
    label: "Creativity",
    description:
      "Capacity to imagine, combine, express, and produce original forms or solutions.",
    category: "creative",
    primaryPlanets: [
      "Venus",
      "Moon",
    ],
    supportingPlanets: [
      "Sun",
      "Mercury",
      "Rahu",
    ],
    themeKeys: [
      "creativity",
      "design",
      "storytelling",
      "imagination",
      "symbolic_art",
      "media",
      "branding",
      "creative_leadership",
    ],
    influenceThemeKeys: [
      "branding",
      "media",
      "public_appeal",
      "symbolic_art",
    ],
    limitationKeys: [
      "approval_seeking",
      "emotional_instability",
      "vanity",
      "restlessness",
    ],
    baseWeight: 9,
  },
  {
    key: "communication",
    label: "Communication",
    description:
      "Capacity to express, explain, write, present, listen, and adapt messages to audiences.",
    category: "creative",
    primaryPlanets: [
      "Mercury",
      "Moon",
    ],
    supportingPlanets: [
      "Venus",
      "Sun",
      "Jupiter",
    ],
    themeKeys: [
      "communication",
      "writing",
      "storytelling",
      "teaching",
      "consulting",
      "public_speaking",
      "media",
      "communication_led_profession",
    ],
    influenceThemeKeys: [
      "communication",
      "teaching",
      "client_experience",
      "media",
    ],
    limitationKeys: [
      "communication_gaps",
      "overthinking",
      "restricted_speech",
      "overgeneralisation",
    ],
    baseWeight: 10,
  },
  {
    key: "storytelling",
    label: "Storytelling",
    description:
      "Capacity to turn ideas and experiences into emotionally engaging narratives.",
    category: "creative",
    primaryPlanets: [
      "Moon",
      "Mercury",
    ],
    supportingPlanets: [
      "Venus",
      "Jupiter",
      "Rahu",
    ],
    themeKeys: [
      "storytelling",
      "writing",
      "media",
      "publishing",
      "emotional_appeal",
      "public_appeal",
      "communication",
    ],
    influenceThemeKeys: [
      "media",
      "publishing",
      "communication",
      "public_appeal",
    ],
    limitationKeys: [
      "emotional_overreaction",
      "overgeneralisation",
      "inflated_promises",
      "restlessness",
    ],
    baseWeight: 8,
  },
  {
    key: "media",
    label: "Media",
    description:
      "Capacity to attract attention, shape public perception, distribute messages, and build audience reach.",
    category: "creative",
    primaryPlanets: [
      "Rahu",
      "Mercury",
      "Venus",
    ],
    supportingPlanets: [
      "Moon",
      "Sun",
    ],
    themeKeys: [
      "media",
      "branding",
      "digital_platforms",
      "public_appeal",
      "mass_attraction",
      "communication",
      "technology",
      "storytelling",
    ],
    influenceThemeKeys: [
      "media",
      "branding",
      "digital_platforms",
      "mass_appeal",
      "public_appeal",
    ],
    limitationKeys: [
      "recognition_obsession",
      "instability",
      "vanity",
      "inflated_promises",
    ],
    baseWeight: 9,
  },
  {
    key: "relationships",
    label: "Relationships",
    description:
      "Capacity to form, sustain, understand, and repair interpersonal bonds.",
    category: "human",
    primaryPlanets: [
      "Venus",
      "Moon",
    ],
    supportingPlanets: [
      "Jupiter",
      "Mercury",
      "Saturn",
    ],
    themeKeys: [
      "relationships",
      "partnerships",
      "care",
      "empathy",
      "diplomacy",
      "public_trust",
      "relationship_responsiveness",
      "counselling",
    ],
    influenceThemeKeys: [
      "relationships",
      "care",
      "public_trust",
      "guidance",
    ],
    limitationKeys: [
      "dependency",
      "relationship_withdrawal",
      "approval_dependence",
      "domination",
    ],
    baseWeight: 10,
  },
  {
    key: "empathy",
    label: "Empathy",
    description:
      "Capacity to perceive emotion, understand another person's experience, and respond with care.",
    category: "human",
    primaryPlanets: [
      "Moon",
      "Venus",
      "Jupiter",
    ],
    supportingPlanets: [
      "Mercury",
      "Ketu",
    ],
    themeKeys: [
      "empathy",
      "care",
      "counselling",
      "emotional_wisdom",
      "public_sensitivity",
      "compassion",
      "customer_understanding",
    ],
    influenceThemeKeys: [
      "care",
      "emotional_wisdom",
      "public_trust",
      "customer_understanding",
    ],
    limitationKeys: [
      "emotional_overreaction",
      "dependency",
      "poor_boundaries",
      "emotional_withdrawal",
    ],
    baseWeight: 9,
  },
  {
    key: "teaching",
    label: "Teaching",
    description:
      "Capacity to explain, guide, structure learning, and transmit knowledge effectively.",
    category: "human",
    primaryPlanets: [
      "Jupiter",
      "Mercury",
    ],
    supportingPlanets: [
      "Moon",
      "Sun",
    ],
    themeKeys: [
      "teaching",
      "guidance",
      "education",
      "consulting",
      "knowledge_synthesis",
      "publishing",
      "counselling",
    ],
    influenceThemeKeys: [
      "teaching",
      "knowledge",
      "guidance",
      "publishing",
    ],
    limitationKeys: [
      "preaching",
      "overconfidence_in_beliefs",
      "overgeneralisation",
      "excessive_theorising",
    ],
    baseWeight: 10,
  },
  {
    key: "healing",
    label: "Healing",
    description:
      "Capacity to support recovery, relief, integration, care, and restoration.",
    category: "human",
    primaryPlanets: [
      "Moon",
      "Jupiter",
      "Ketu",
    ],
    supportingPlanets: [
      "Venus",
      "Sun",
      "Saturn",
    ],
    themeKeys: [
      "healing",
      "care",
      "health_care",
      "counselling",
      "recovery",
      "diagnosis",
      "spiritual_healing",
      "service",
    ],
    influenceThemeKeys: [
      "care",
      "healing",
      "diagnostics",
      "guidance",
    ],
    limitationKeys: [
      "emotional_heaviness",
      "withdrawal",
      "poor_boundaries",
      "burnout",
    ],
    baseWeight: 9,
  },
  {
    key: "mentoring",
    label: "Mentoring",
    description:
      "Capacity to guide growth through experience, judgement, encouragement, and practical advice.",
    category: "human",
    primaryPlanets: [
      "Jupiter",
      "Saturn",
    ],
    supportingPlanets: [
      "Sun",
      "Mercury",
      "Moon",
    ],
    themeKeys: [
      "mentoring",
      "guidance",
      "counselling",
      "teaching",
      "mature_judgement",
      "responsibility",
      "consulting",
    ],
    influenceThemeKeys: [
      "guidance",
      "teaching",
      "responsibility",
      "knowledge",
    ],
    limitationKeys: [
      "preaching",
      "pessimism",
      "rigidity",
      "overconfidence_in_beliefs",
    ],
    baseWeight: 9,
  },
  {
    key: "dharma",
    label: "Dharma",
    description:
      "Capacity to act from purpose, conscience, ethics, and a meaningful life direction.",
    category: "spiritual",
    primaryPlanets: [
      "Jupiter",
      "Sun",
    ],
    supportingPlanets: [
      "Ketu",
      "Moon",
      "Saturn",
    ],
    themeKeys: [
      "dharma",
      "purpose",
      "ethics",
      "philosophy",
      "spiritual_purpose",
      "law",
      "guidance",
      "integrity",
    ],
    influenceThemeKeys: [
      "ethics",
      "guidance",
      "philosophy",
      "purpose",
    ],
    limitationKeys: [
      "dogmatism",
      "self_righteousness",
      "rejection_of_teachers",
      "rigidity",
    ],
    baseWeight: 10,
  },
  {
    key: "detachment",
    label: "Detachment",
    description:
      "Capacity to release attachment, observe without over-identification, and move beyond surface desire.",
    category: "spiritual",
    primaryPlanets: [
      "Ketu",
      "Saturn",
    ],
    supportingPlanets: [
      "Jupiter",
      "Moon",
    ],
    themeKeys: [
      "detachment",
      "austerity",
      "spirituality",
      "surrender",
      "inner_mastery",
      "liberation",
      "hidden_work",
    ],
    influenceThemeKeys: [
      "detachment",
      "austerity",
      "spirituality",
      "inner_mastery",
    ],
    limitationKeys: [
      "withdrawal",
      "indifference",
      "disconnection",
      "low_motivation",
    ],
    baseWeight: 9,
  },
  {
    key: "transformation",
    label: "Transformation",
    description:
      "Capacity to face disruption, release old patterns, and rebuild at a deeper level.",
    category: "spiritual",
    primaryPlanets: [
      "Ketu",
      "Mars",
      "Saturn",
    ],
    supportingPlanets: [
      "Rahu",
      "Moon",
      "Jupiter",
    ],
    themeKeys: [
      "transformation",
      "crisis_mastery",
      "hidden_systems",
      "investigation",
      "psychological_depth",
      "rebirth",
      "healing",
    ],
    influenceThemeKeys: [
      "transformation",
      "crisis",
      "hidden_systems",
      "detachment",
    ],
    limitationKeys: [
      "extreme_withdrawal",
      "fear_of_loss",
      "instability",
      "control",
    ],
    baseWeight: 10,
  },
  {
    key: "intuition",
    label: "Intuition",
    description:
      "Capacity to perceive subtle patterns, emotional signals, and non-linear connections.",
    category: "spiritual",
    primaryPlanets: [
      "Moon",
      "Ketu",
    ],
    supportingPlanets: [
      "Jupiter",
      "Venus",
      "Mercury",
    ],
    themeKeys: [
      "intuition",
      "subtle_perception",
      "spiritual_sensitivity",
      "hidden_pattern_memory",
      "imagination",
      "emotional_wisdom",
      "astrology",
    ],
    influenceThemeKeys: [
      "intuition",
      "subtle_perception",
      "spiritual_sensitivity",
      "symbolic_analysis",
    ],
    limitationKeys: [
      "emotional_instability",
      "confusion",
      "withdrawal",
      "poor_boundaries",
    ],
    baseWeight: 9,
  },
  {
    key: "mysticism",
    label: "Mysticism",
    description:
      "Capacity for occult study, symbolic understanding, contemplative depth, and spiritual insight.",
    category: "spiritual",
    primaryPlanets: [
      "Ketu",
      "Jupiter",
    ],
    supportingPlanets: [
      "Moon",
      "Rahu",
      "Mercury",
    ],
    themeKeys: [
      "mysticism",
      "occult_knowledge",
      "astrology",
      "spiritual_philosophy",
      "scripture",
      "meditation",
      "subtle_perception",
      "hidden_systems",
    ],
    influenceThemeKeys: [
      "occult_knowledge",
      "spiritual_philosophy",
      "scripture",
      "symbolic_analysis",
    ],
    limitationKeys: [
      "dogmatism",
      "withdrawal",
      "rejection_of_practical_guidance",
      "escapism",
    ],
    baseWeight: 10,
  },
];