import type {
  PlanetName,
} from "../contracts/facts";

import type {
  KnowledgeCategory,
} from "./types";

export type NakshatraMotivation =
  | "dharma"
  | "artha"
  | "kama"
  | "moksha";

export type NakshatraProfile = {
  key: string;
  label: string;
  ruler: PlanetName;
  deity: string;
  motivation: NakshatraMotivation;
  primaryCategory: KnowledgeCategory;
  themes: string[];
  capabilityThemes: string[];

  intelligenceStyle: string[];
  learningStyle: string[];
  communicationStyle: string[];
  businessStyle: string[];
  relationshipStyle: string[];
  spiritualStyle: string[];
  decisionStyle: string[];

  strengthens: string[];
  shadows: string[];
  score: number;
};

export const NAKSHATRA_PROFILES: NakshatraProfile[] = [
  {
    key: "ashwini",
    label: "Ashwini",
    ruler: "Ketu",
    deity: "Ashwini Kumaras",
    motivation: "dharma",
    primaryCategory: "career",
    themes: ["initiative", "rapid response", "healing", "diagnosis", "new beginnings"],
    capabilityThemes: ["initiative", "diagnosis", "healing", "problem_solving"],
    intelligenceStyle: ["rapid diagnosis", "first-response thinking", "solution seeking"],
    learningStyle: ["learns quickly by doing", "prefers practical experimentation"],
    communicationStyle: ["direct", "fast", "solution-oriented"],
    businessStyle: ["startup energy", "speed", "independent execution"],
    relationshipStyle: ["needs space", "responds quickly but may move too fast"],
    spiritualStyle: ["healing", "renewal", "restorative action"],
    decisionStyle: ["fast decisions", "acts before full certainty"],
    strengthens: ["speed", "independent action", "problem solving"],
    shadows: ["impatience", "premature action"],
    score: 7,
  },
  {
    key: "bharani",
    label: "Bharani",
    ruler: "Venus",
    deity: "Yama",
    motivation: "artha",
    primaryCategory: "psychology",
    themes: ["responsibility", "boundaries", "consequence", "transformation", "endurance"],
    capabilityThemes: ["responsibility", "transformation", "endurance", "decision_making"],
    intelligenceStyle: ["consequence awareness", "ethical pressure testing", "transformational thinking"],
    learningStyle: ["learns through responsibility", "absorbs lessons through lived consequences"],
    communicationStyle: ["serious", "boundary-conscious", "intense"],
    businessStyle: ["risk containment", "compliance", "high-responsibility environments"],
    relationshipStyle: ["deep commitment", "strong boundaries", "intensity"],
    spiritualStyle: ["karma", "discipline", "acceptance of consequence"],
    decisionStyle: ["weighs duty and consequence", "can become controlling"],
    strengthens: ["ethical judgement", "capacity under pressure"],
    shadows: ["intensity", "control"],
    score: 7,
  },
  {
    key: "krittika",
    label: "Krittika",
    ruler: "Sun",
    deity: "Agni",
    motivation: "kama",
    primaryCategory: "communication",
    themes: ["discernment", "purification", "precision", "separation", "critique"],
    capabilityThemes: ["analysis", "diagnosis", "decision_making", "communication"],
    intelligenceStyle: ["discrimination", "editing", "separation of signal from noise"],
    learningStyle: ["learns by critique", "improves through correction"],
    communicationStyle: ["clear", "sharp", "precise"],
    businessStyle: ["quality control", "editing", "auditing", "standards"],
    relationshipStyle: ["honest but can be cutting", "high standards"],
    spiritualStyle: ["purification", "discernment", "truth through removal"],
    decisionStyle: ["decisive", "cuts away weak options"],
    strengthens: ["clarity", "editing", "decisive judgement"],
    shadows: ["harsh criticism", "cutting expression"],
    score: 7,
  },
  {
    key: "rohini",
    label: "Rohini",
    ruler: "Moon",
    deity: "Prajapati",
    motivation: "moksha",
    primaryCategory: "business",
    themes: ["growth", "cultivation", "beauty", "resources", "creation"],
    capabilityThemes: ["creativity", "customer_understanding", "wealth_accumulation", "relationships"],
    intelligenceStyle: ["growth-oriented", "resource-aware", "creative development"],
    learningStyle: ["learns through repetition and cultivation", "prefers stable development"],
    communicationStyle: ["pleasant", "persuasive", "sensory"],
    businessStyle: ["value creation", "branding", "luxury", "agriculture", "consumer appeal"],
    relationshipStyle: ["affectionate", "attached", "nurturing"],
    spiritualStyle: ["creation", "abundance", "gratitude"],
    decisionStyle: ["prefers sustainable growth", "may resist giving up comfort"],
    strengthens: ["value creation", "attraction", "product development"],
    shadows: ["attachment", "material indulgence"],
    score: 7,
  },
  {
    key: "mrigashira",
    label: "Mrigashira",
    ruler: "Mars",
    deity: "Soma",
    motivation: "moksha",
    primaryCategory: "education",
    themes: ["curiosity", "search", "exploration", "research", "information gathering"],
    capabilityThemes: ["research", "investigation", "curiosity", "learning", "analysis"],
    intelligenceStyle: ["curious", "comparative", "search-driven"],
    learningStyle: ["learns by questioning", "researches alternatives"],
    communicationStyle: ["inquisitive", "adaptive", "exploratory"],
    businessStyle: ["research", "market discovery", "consulting", "product search"],
    relationshipStyle: ["needs intellectual freshness", "can remain unsettled"],
    spiritualStyle: ["quest for meaning", "seeking"],
    decisionStyle: ["keeps options open", "can delay commitment through searching"],
    strengthens: ["inquiry", "comparison", "adaptability"],
    shadows: ["restlessness", "never-ending search"],
    score: 7,
  },
  {
    key: "ardra",
    label: "Ardra",
    ruler: "Rahu",
    deity: "Rudra",
    motivation: "kama",
    primaryCategory: "career",
    themes: ["disruption", "complexity", "technology", "crisis", "reconstruction"],
    capabilityThemes: ["research", "analysis", "innovation", "technology", "diagnostics"],
    intelligenceStyle: ["complex systems thinking", "crisis analysis", "disruptive insight"],
    learningStyle: ["learns through breakdown and reconstruction", "handles difficult material"],
    communicationStyle: ["intense", "technical", "provocative"],
    businessStyle: ["technology", "turnaround", "crisis management", "innovation"],
    relationshipStyle: ["emotionally intense", "needs honesty during turbulence"],
    spiritualStyle: ["destruction before renewal", "confronting reality"],
    decisionStyle: ["acts strongly under crisis", "can overcorrect"],
    strengthens: ["deep analysis", "innovation", "crisis intelligence"],
    shadows: ["mental turbulence", "destructive intensity"],
    score: 8,
  },
  {
    key: "punarvasu",
    label: "Punarvasu",
    ruler: "Jupiter",
    deity: "Aditi",
    motivation: "artha",
    primaryCategory: "education",
    themes: ["renewal", "restoration", "return", "teaching", "reframing"],
    capabilityThemes: ["learning", "teaching", "guidance", "knowledge_synthesis", "healing"],
    intelligenceStyle: ["reframing", "restoration", "big-picture synthesis"],
    learningStyle: ["learns through return and revision", "teaches by simplifying"],
    communicationStyle: ["reassuring", "explanatory", "constructive"],
    businessStyle: ["education", "advisory", "recovery", "renewal businesses"],
    relationshipStyle: ["forgiving", "restorative", "family-oriented"],
    spiritualStyle: ["renewal", "faith", "return to principles"],
    decisionStyle: ["reconsiders and resets", "may repeat cycles"],
    strengthens: ["explanation", "resilience", "knowledge renewal"],
    shadows: ["repetition", "returning to old patterns"],
    score: 7,
  },
  {
    key: "pushya",
    label: "Pushya",
    ruler: "Saturn",
    deity: "Brihaspati",
    motivation: "dharma",
    primaryCategory: "education",
    themes: ["nourishment", "discipline", "teaching", "institutions", "responsibility"],
    capabilityThemes: ["teaching", "mentoring", "guidance", "responsibility", "discipline"],
    intelligenceStyle: ["structured wisdom", "institutional thinking", "mentoring"],
    learningStyle: ["disciplined study", "teacher-guided learning"],
    communicationStyle: ["responsible", "measured", "instructional"],
    businessStyle: ["institutions", "education", "governance", "service"],
    relationshipStyle: ["protective", "dependable", "duty-oriented"],
    spiritualStyle: ["discipline", "service", "devotion to knowledge"],
    decisionStyle: ["conservative", "duty-first", "reliable"],
    strengthens: ["mentoring", "structured learning", "guidance"],
    shadows: ["rigidity", "over-responsibility"],
    score: 8,
  },
  {
    key: "ashlesha",
    label: "Ashlesha",
    ruler: "Mercury",
    deity: "Nagas",
    motivation: "dharma",
    primaryCategory: "psychology",
    themes: ["psychology", "strategy", "hidden motives", "persuasion", "complexity"],
    capabilityThemes: ["analysis", "investigation", "pattern_recognition", "strategic_thinking", "psychological_depth"],
    intelligenceStyle: ["penetrating psychology", "strategic reading", "hidden-pattern analysis"],
    learningStyle: ["learns through depth", "tracks motives and subtext"],
    communicationStyle: ["persuasive", "layered", "strategic"],
    businessStyle: ["negotiation", "intelligence", "psychology", "confidential work"],
    relationshipStyle: ["intense bonding", "high sensitivity to trust"],
    spiritualStyle: ["serpent symbolism", "hidden knowledge", "inner transformation"],
    decisionStyle: ["strategic", "calculating", "may become suspicious"],
    strengthens: ["penetrating analysis", "confidential intelligence", "pattern recognition"],
    shadows: ["manipulation", "suspicion", "entanglement"],
    score: 8,
  },
  {
    key: "magha",
    label: "Magha",
    ruler: "Ketu",
    deity: "Pitris",
    motivation: "artha",
    primaryCategory: "career",
    themes: ["legacy", "lineage", "authority", "heritage", "institutional memory"],
    capabilityThemes: ["leadership", "authority", "responsibility", "governance", "dharma"],
    intelligenceStyle: ["legacy-conscious", "hierarchical", "authority-centered"],
    learningStyle: ["learns through tradition", "values lineage and precedent"],
    communicationStyle: ["formal", "authoritative", "status-aware"],
    businessStyle: ["leadership", "institutions", "heritage", "government"],
    relationshipStyle: ["protective", "proud", "expects respect"],
    spiritualStyle: ["ancestral connection", "lineage", "ritual continuity"],
    decisionStyle: ["authority-led", "tradition-sensitive"],
    strengthens: ["leadership", "tradition", "responsibility"],
    shadows: ["status attachment", "ancestral rigidity"],
    score: 7,
  },
  {
    key: "purva_phalguni",
    label: "Purva Phalguni",
    ruler: "Venus",
    deity: "Bhaga",
    motivation: "kama",
    primaryCategory: "relationships",
    themes: ["creativity", "pleasure", "attraction", "social connection", "art"],
    capabilityThemes: ["creativity", "relationships", "customer_understanding", "communication", "media"],
    intelligenceStyle: ["creative", "social", "pleasure-oriented"],
    learningStyle: ["learns through expression", "artistic and experiential learning"],
    communicationStyle: ["warm", "charming", "engaging"],
    businessStyle: ["creative industries", "media", "hospitality", "luxury"],
    relationshipStyle: ["romantic", "affectionate", "pleasure-seeking"],
    spiritualStyle: ["joy", "beauty", "creative offering"],
    decisionStyle: ["chooses what feels attractive", "may avoid effort"],
    strengthens: ["charisma", "creative expression", "relationship building"],
    shadows: ["indulgence", "avoidance of effort"],
    score: 7,
  },
  {
    key: "uttara_phalguni",
    label: "Uttara Phalguni",
    ruler: "Sun",
    deity: "Aryaman",
    motivation: "moksha",
    primaryCategory: "business",
    themes: ["agreements", "service", "contracts", "patronage", "commitment"],
    capabilityThemes: ["relationships", "negotiation", "responsibility", "governance", "consulting"],
    intelligenceStyle: ["contractual", "service-oriented", "organised"],
    learningStyle: ["learns through responsibility and partnership"],
    communicationStyle: ["reliable", "formal", "agreement-focused"],
    businessStyle: ["partnerships", "contracts", "professional services"],
    relationshipStyle: ["committed", "cooperative", "duty-aware"],
    spiritualStyle: ["service", "right relationship", "social dharma"],
    decisionStyle: ["weighs commitments", "long-term oriented"],
    strengthens: ["partnership management", "professional reliability", "organisation"],
    shadows: ["obligation", "over-commitment"],
    score: 7,
  },
  {
    key: "hasta",
    label: "Hasta",
    ruler: "Moon",
    deity: "Savitar",
    motivation: "moksha",
    primaryCategory: "career",
    themes: ["skill", "craft", "execution", "precision", "practical intelligence"],
    capabilityThemes: ["execution", "analysis", "diagnosis", "problem_solving", "technical_mastery"],
    intelligenceStyle: ["practical", "precise", "hands-on"],
    learningStyle: ["learns by doing", "masters technique through repetition"],
    communicationStyle: ["clear", "practical", "detail-oriented"],
    businessStyle: ["craft", "operations", "implementation", "technical services"],
    relationshipStyle: ["helpful", "competent", "can become controlling"],
    spiritualStyle: ["skill as service", "manifestation"],
    decisionStyle: ["practical", "execution-focused", "detail-driven"],
    strengthens: ["hands-on ability", "detail", "implementation"],
    shadows: ["over-control", "perfectionism"],
    score: 8,
  },
  {
    key: "chitra",
    label: "Chitra",
    ruler: "Mars",
    deity: "Tvashtar",
    motivation: "kama",
    primaryCategory: "business",
    themes: ["design", "construction", "beauty", "architecture", "technical creativity"],
    capabilityThemes: ["creativity", "innovation", "design", "engineering", "execution"],
    intelligenceStyle: ["design thinking", "structural creativity", "visual intelligence"],
    learningStyle: ["learns through construction and refinement"],
    communicationStyle: ["stylish", "precise", "image-aware"],
    businessStyle: ["design", "architecture", "engineering", "branding"],
    relationshipStyle: ["attracted to beauty and individuality"],
    spiritualStyle: ["sacred design", "creation through form"],
    decisionStyle: ["chooses elegant solutions", "can overfocus on appearance"],
    strengthens: ["innovation", "product creation", "visual intelligence"],
    shadows: ["image fixation", "perfectionism"],
    score: 7,
  },
  {
    key: "swati",
    label: "Swati",
    ruler: "Rahu",
    deity: "Vayu",
    motivation: "artha",
    primaryCategory: "business",
    themes: ["independence", "trade", "movement", "networks", "flexibility"],
    capabilityThemes: ["entrepreneurship", "commerce", "negotiation", "scale", "innovation"],
    intelligenceStyle: ["independent", "market-aware", "adaptive"],
    learningStyle: ["self-directed learning", "learns through exposure and movement"],
    communicationStyle: ["diplomatic", "flexible", "negotiating"],
    businessStyle: ["trade", "entrepreneurship", "international business", "networks"],
    relationshipStyle: ["needs freedom", "negotiates boundaries"],
    spiritualStyle: ["freedom", "movement", "self-direction"],
    decisionStyle: ["independent", "opportunity-driven", "can become unstable"],
    strengthens: ["entrepreneurship", "negotiation", "international exchange"],
    shadows: ["instability", "excess independence"],
    score: 8,
  },
  {
    key: "vishakha",
    label: "Vishakha",
    ruler: "Jupiter",
    deity: "Indra-Agni",
    motivation: "dharma",
    primaryCategory: "career",
    themes: ["goal pursuit", "focus", "achievement", "competition", "strategy"],
    capabilityThemes: ["strategic_thinking", "leadership", "decision_making", "initiative", "dharma"],
    intelligenceStyle: ["goal-oriented", "competitive", "strategic"],
    learningStyle: ["learns with a target", "deepens through focused ambition"],
    communicationStyle: ["persuasive", "purposeful", "driven"],
    businessStyle: ["sales", "leadership", "strategy", "competitive growth"],
    relationshipStyle: ["loyal to goals", "can prioritise ambition"],
    spiritualStyle: ["focused aspiration", "purpose"],
    decisionStyle: ["results-driven", "persistent", "can become obsessive"],
    strengthens: ["determination", "persuasion", "long-range goals"],
    shadows: ["obsession with outcomes", "over-competition"],
    score: 8,
  },
  {
    key: "anuradha",
    label: "Anuradha",
    ruler: "Saturn",
    deity: "Mitra",
    motivation: "dharma",
    primaryCategory: "relationships",
    themes: ["friendship", "loyalty", "networks", "cooperation", "devotion"],
    capabilityThemes: ["relationships", "empathy", "negotiation", "mentoring", "responsibility"],
    intelligenceStyle: ["relational intelligence", "network thinking", "loyalty-based judgement"],
    learningStyle: ["learns through collaboration", "values trusted teachers"],
    communicationStyle: ["diplomatic", "cooperative", "relationship-aware"],
    businessStyle: ["partnerships", "alliances", "client relationships"],
    relationshipStyle: ["loyal", "devoted", "friendship-based"],
    spiritualStyle: ["devotion", "friendship", "discipline in relationships"],
    decisionStyle: ["considers alliances", "patient and cooperative"],
    strengthens: ["collaboration", "diplomacy", "relationship durability"],
    shadows: ["dependence on alliances", "emotional restraint"],
    score: 7,
  },
  {
    key: "jyeshtha",
    label: "Jyeshtha",
    ruler: "Mercury",
    deity: "Indra",
    motivation: "artha",
    primaryCategory: "career",
    themes: ["seniority", "protection", "authority", "strategy", "confidential knowledge"],
    capabilityThemes: ["authority", "strategic_thinking", "investigation", "governance", "decision_making"],
    intelligenceStyle: ["strategic seniority", "risk awareness", "protective intelligence"],
    learningStyle: ["learns from responsibility and pressure"],
    communicationStyle: ["authoritative", "guarded", "strategic"],
    businessStyle: ["risk management", "leadership", "confidential sectors"],
    relationshipStyle: ["protective", "proud", "can become defensive"],
    spiritualStyle: ["responsibility", "protection", "earned authority"],
    decisionStyle: ["risk-conscious", "protective", "high-control"],
    strengthens: ["risk management", "leadership under pressure", "investigation"],
    shadows: ["defensiveness", "superiority"],
    score: 8,
  },
  {
    key: "mula",
    label: "Mula",
    ruler: "Ketu",
    deity: "Nirriti",
    motivation: "kama",
    primaryCategory: "spirituality",
    themes: ["roots", "origins", "dismantling", "research", "hidden causes"],
    capabilityThemes: ["research", "investigation", "analysis", "pattern_recognition", "occult_knowledge", "hidden_systems"],
    intelligenceStyle: ["root-cause analysis", "first-principles thinking", "hidden-system investigation"],
    learningStyle: ["learns by dismantling assumptions", "goes to origins rather than surface explanations"],
    communicationStyle: ["probing", "direct", "research-led"],
    businessStyle: ["research", "forensics", "deep advisory", "specialist consulting"],
    relationshipStyle: ["seeks truth beneath appearances", "can destabilise weak bonds"],
    spiritualStyle: ["occult inquiry", "karmic roots", "liberation through truth"],
    decisionStyle: ["cuts to root causes", "can reject superficial compromises"],
    strengthens: ["root-cause analysis", "first-principles thinking", "deep investigation"],
    shadows: ["destructive inquiry", "obsession with ultimate causes"],
    score: 9,
  },
  {
    key: "purva_ashadha",
    label: "Purva Ashadha",
    ruler: "Venus",
    deity: "Apas",
    motivation: "moksha",
    primaryCategory: "communication",
    themes: ["advocacy", "persuasion", "conviction", "renewal", "campaigning"],
    capabilityThemes: ["communication", "leadership", "teaching", "dharma", "storytelling"],
    intelligenceStyle: ["conviction-led", "persuasive", "campaign-oriented"],
    learningStyle: ["learns through advocacy", "strengthens through debate"],
    communicationStyle: ["influential", "assertive", "belief-driven"],
    businessStyle: ["marketing", "public relations", "advocacy", "campaigns"],
    relationshipStyle: ["passionate", "idealistic", "can be uncompromising"],
    spiritualStyle: ["purification", "renewal of conviction"],
    decisionStyle: ["belief-led", "persistent", "can resist correction"],
    strengthens: ["influence", "public communication", "belief-led action"],
    shadows: ["argument from conviction", "resistance to correction"],
    score: 7,
  },
  {
    key: "uttara_ashadha",
    label: "Uttara Ashadha",
    ruler: "Sun",
    deity: "Vishvadevas",
    motivation: "moksha",
    primaryCategory: "career",
    themes: ["durability", "principles", "governance", "responsibility", "lasting achievement"],
    capabilityThemes: ["leadership", "governance", "responsibility", "strategic_thinking", "dharma"],
    intelligenceStyle: ["principled", "long-range", "governance-minded"],
    learningStyle: ["learns through responsibility and universal principles"],
    communicationStyle: ["formal", "principled", "authoritative"],
    businessStyle: ["governance", "policy", "leadership", "institution building"],
    relationshipStyle: ["reliable", "principled", "duty-oriented"],
    spiritualStyle: ["universal values", "dharma", "lasting achievement"],
    decisionStyle: ["long-term", "principle-first", "durable"],
    strengthens: ["leadership", "policy", "long-term strategy"],
    shadows: ["rigidity", "burden of responsibility"],
    score: 8,
  },
  {
    key: "shravana",
    label: "Shravana",
    ruler: "Moon",
    deity: "Vishnu",
    motivation: "artha",
    primaryCategory: "education",
    themes: ["listening", "learning", "language", "knowledge transmission", "observation"],
    capabilityThemes: ["learning", "teaching", "communication", "mentoring", "knowledge"],
    intelligenceStyle: ["observational", "language-based", "knowledge-transmission oriented"],
    learningStyle: ["excellent listening", "learns from teachers, texts and repetition"],
    communicationStyle: ["clear", "educational", "receptive"],
    businessStyle: ["education", "media", "consulting", "communication"],
    relationshipStyle: ["listens well", "needs respectful communication"],
    spiritualStyle: ["sacred listening", "preservation of knowledge"],
    decisionStyle: ["gathers information first", "may be influenced by opinion"],
    strengthens: ["teaching", "communication", "counselling"],
    shadows: ["over-reliance on received knowledge", "sensitivity to opinion"],
    score: 8,
  },
  {
    key: "dhanishtha",
    label: "Dhanishtha",
    ruler: "Mars",
    deity: "Vasus",
    motivation: "dharma",
    primaryCategory: "business",
    themes: ["coordination", "resources", "timing", "networks", "achievement"],
    capabilityThemes: ["operations", "leadership", "scale", "commerce", "execution"],
    intelligenceStyle: ["resource coordination", "timing awareness", "group systems"],
    learningStyle: ["learns through execution and team rhythm"],
    communicationStyle: ["confident", "organising", "goal-driven"],
    businessStyle: ["operations", "finance", "networks", "large teams"],
    relationshipStyle: ["socially capable", "achievement-conscious"],
    spiritualStyle: ["right use of resources", "collective contribution"],
    decisionStyle: ["practical", "resource-led", "timing-sensitive"],
    strengthens: ["organisation", "resource management", "group coordination"],
    shadows: ["status competition", "restless ambition"],
    score: 7,
  },
  {
    key: "shatabhisha",
    label: "Shatabhisha",
    ruler: "Rahu",
    deity: "Varuna",
    motivation: "dharma",
    primaryCategory: "career",
    themes: ["systems", "healing", "research", "technology", "diagnosis"],
    capabilityThemes: ["research", "diagnostics", "technology", "innovation", "healing", "hidden_systems"],
    intelligenceStyle: ["systems analysis", "diagnostic thinking", "technical research"],
    learningStyle: ["independent research", "data and systems learning"],
    communicationStyle: ["technical", "objective", "reserved"],
    businessStyle: ["technology", "health systems", "research", "analytics"],
    relationshipStyle: ["needs space", "can become detached"],
    spiritualStyle: ["healing through truth", "mystery", "solitude"],
    decisionStyle: ["evidence-driven", "independent", "can isolate"],
    strengthens: ["data analysis", "innovation", "specialist research"],
    shadows: ["isolation", "over-intellectualisation"],
    score: 8,
  },
  {
    key: "purva_bhadrapada",
    label: "Purva Bhadrapada",
    ruler: "Jupiter",
    deity: "Aja Ekapada",
    motivation: "artha",
    primaryCategory: "spirituality",
    themes: ["intensity", "philosophy", "reform", "symbolism", "transformation"],
    capabilityThemes: ["mysticism", "transformation", "research", "dharma", "teaching"],
    intelligenceStyle: ["philosophical intensity", "symbolic thinking", "reformist insight"],
    learningStyle: ["learns through extremes and deep philosophy"],
    communicationStyle: ["intense", "visionary", "transformative"],
    businessStyle: ["research", "teaching", "reform", "spiritual advisory"],
    relationshipStyle: ["deep", "idealistic", "can become severe"],
    spiritualStyle: ["mysticism", "transformation", "renunciation of superficiality"],
    decisionStyle: ["principle-heavy", "transformational", "can become extreme"],
    strengthens: ["occult inquiry", "deep thought", "transformative teaching"],
    shadows: ["extremism", "intellectual severity"],
    score: 8,
  },
  {
    key: "uttara_bhadrapada",
    label: "Uttara Bhadrapada",
    ruler: "Saturn",
    deity: "Ahir Budhnya",
    motivation: "kama",
    primaryCategory: "spirituality",
    themes: ["depth", "patience", "stability", "contemplation", "inner knowledge"],
    capabilityThemes: ["mysticism", "mentoring", "healing", "discipline", "detachment"],
    intelligenceStyle: ["deep contemplation", "mature judgement", "patient synthesis"],
    learningStyle: ["slow deep learning", "absorbs through reflection"],
    communicationStyle: ["calm", "measured", "wise"],
    businessStyle: ["advisory", "counselling", "institutional stewardship"],
    relationshipStyle: ["steady", "compassionate", "emotionally contained"],
    spiritualStyle: ["inner depth", "discipline", "contemplation"],
    decisionStyle: ["slow and mature", "stable", "can delay action"],
    strengthens: ["counselling", "spiritual discipline", "mature judgement"],
    shadows: ["withdrawal", "emotional heaviness"],
    score: 8,
  },
  {
    key: "revati",
    label: "Revati",
    ruler: "Mercury",
    deity: "Pushan",
    motivation: "moksha",
    primaryCategory: "communication",
    themes: ["guidance", "navigation", "completion", "travel", "compassion"],
    capabilityThemes: ["communication", "guidance", "healing", "relationships", "storytelling"],
    intelligenceStyle: ["guiding", "integrative", "navigation-oriented"],
    learningStyle: ["learns by connecting ideas", "supports others through explanation"],
    communicationStyle: ["gentle", "supportive", "clear"],
    businessStyle: ["consulting", "guidance", "travel", "education", "client service"],
    relationshipStyle: ["compassionate", "supportive", "may need stronger boundaries"],
    spiritualStyle: ["completion", "guidance", "safe passage"],
    decisionStyle: ["supportive", "integrative", "can become diffuse"],
    strengthens: ["counselling", "communication", "supportive guidance"],
    shadows: ["diffusion", "poor boundaries"],
    score: 7,
  },
];

export const NAKSHATRA_PROFILE_BY_LABEL:
  Record<string, NakshatraProfile | undefined> =
  Object.fromEntries(
    NAKSHATRA_PROFILES.map(
      (profile) => [
        profile.label,
        profile,
      ]
    )
  );