import type {
  CertificationQuestion,
} from "./types";

export const PROFESSION_CERTIFICATION:
  CertificationQuestion[] = [
  {
    id: "profession_astrologer",
    category: "profession",
    question: "Should I become an astrologer?",
    expectedCapabilities: [
      "research",
      "analysis",
      "mysticism",
    ],
    preferredCapabilities: [
      "communication",
      "teaching",
      "dharma",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Jupiter",
      "Ketu",
    ],
    expectedEvidence: [
      "Research",
      "Occult",
      "Teaching",
      "Knowledge",
    ],
    expectedThemes: [
      "Analysis",
      "Wisdom",
      "Spirituality",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_teacher",
    category: "profession",
    question: "Should I become a teacher?",
    expectedCapabilities: [
      "knowledge",
      "communication",
      "teaching",
    ],
    preferredCapabilities: [
      "empathy",
      "storytelling",
      "mentoring",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Jupiter",
      "Mercury",
    ],
    expectedEvidence: [
      "Teaching",
      "Education",
      "Knowledge",
    ],
    expectedThemes: [
      "Learning",
      "Communication",
      "Guidance",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_software_engineer",
    category: "profession",
    question: "Should I become a software engineer?",
    expectedCapabilities: [
      "analysis",
      "learning",
      "execution",
    ],
    preferredCapabilities: [
      "innovation",
      "research",
      "discipline",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Mars",
      "Rahu",
    ],
    expectedEvidence: [
      "Technology",
      "Analysis",
      "Technical",
    ],
    expectedThemes: [
      "Systems",
      "Logic",
      "Innovation",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_banker",
    category: "profession",
    question: "Should I become a banker?",
    expectedCapabilities: [
      "analysis",
      "governance",
      "responsibility",
    ],
    preferredCapabilities: [
      "commerce",
      "negotiation",
      "discipline",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Jupiter",
      "Saturn",
    ],
    expectedEvidence: [
      "Finance",
      "Structure",
      "Analysis",
    ],
    expectedThemes: [
      "Wealth",
      "Governance",
      "Commercial",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_doctor",
    category: "profession",
    question: "Should I become a doctor?",
    expectedCapabilities: [
      "knowledge",
      "analysis",
      "healing",
    ],
    preferredCapabilities: [
      "responsibility",
      "communication",
      "research",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mars",
      "Mercury",
      "Jupiter",
    ],
    expectedEvidence: [
      "Healing",
      "Diagnosis",
      "Research",
    ],
    expectedThemes: [
      "Health",
      "Precision",
      "Service",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_lawyer",
    category: "profession",
    question: "Should I become a lawyer?",
    expectedCapabilities: [
      "analysis",
      "communication",
      "negotiation",
    ],
    preferredCapabilities: [
      "knowledge",
      "governance",
      "leadership",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Jupiter",
      "Sun",
    ],
    expectedEvidence: [
      "Argument",
      "Judgement",
      "Communication",
    ],
    expectedThemes: [
      "Logic",
      "Justice",
      "Persuasion",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_politician",
    category: "profession",
    question: "Should I become a politician?",
    expectedCapabilities: [
      "leadership",
      "communication",
      "governance",
    ],
    preferredCapabilities: [
      "authority",
      "strategic_thinking",
      "negotiation",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Sun",
      "Jupiter",
      "Rahu",
    ],
    expectedEvidence: [
      "Leadership",
      "Public",
      "Authority",
    ],
    expectedThemes: [
      "Visibility",
      "Influence",
      "Governance",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_entrepreneur",
    category: "profession",
    question: "Should I become an entrepreneur?",
    expectedCapabilities: [
      "entrepreneurship",
      "leadership",
      "commerce",
    ],
    preferredCapabilities: [
      "initiative",
      "negotiation",
      "innovation",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Mars",
      "Rahu",
    ],
    expectedEvidence: [
      "Business",
      "Initiative",
      "Risk",
    ],
    expectedThemes: [
      "Commerce",
      "Leadership",
      "Growth",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_consultant",
    category: "profession",
    question: "Should I become a consultant?",
    expectedCapabilities: [
      "knowledge",
      "analysis",
      "communication",
    ],
    preferredCapabilities: [
      "strategic_thinking",
      "negotiation",
      "teaching",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Jupiter",
    ],
    expectedEvidence: [
      "Advisory",
      "Analysis",
      "Communication",
    ],
    expectedThemes: [
      "Knowledge",
      "Guidance",
      "Strategy",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_researcher",
    category: "profession",
    question: "Should I become a researcher?",
    expectedCapabilities: [
      "research",
      "analysis",
      "learning",
    ],
    preferredCapabilities: [
      "knowledge",
      "discipline",
      "innovation",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Ketu",
      "Saturn",
    ],
    expectedEvidence: [
      "Research",
      "Investigation",
      "Analysis",
    ],
    expectedThemes: [
      "Depth",
      "Patterns",
      "Learning",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_psychologist",
    category: "profession",
    question: "Should I become a psychologist?",
    expectedCapabilities: [
      "empathy",
      "analysis",
      "communication",
    ],
    preferredCapabilities: [
      "healing",
      "research",
      "intuition",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Moon",
      "Mercury",
      "Ketu",
    ],
    expectedEvidence: [
      "Psychology",
      "Emotional",
      "Analysis",
    ],
    expectedThemes: [
      "Psychological Depth",
      "Empathy",
      "Healing",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_accountant",
    category: "profession",
    question: "Should I become an accountant?",
    expectedCapabilities: [
      "analysis",
      "governance",
      "discipline",
    ],
    preferredCapabilities: [
      "responsibility",
      "operations",
      "knowledge",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Saturn",
    ],
    expectedEvidence: [
      "Numbers",
      "Audit",
      "Finance",
    ],
    expectedThemes: [
      "Precision",
      "Structure",
      "Analysis",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_journalist",
    category: "profession",
    question: "Should I become a journalist?",
    expectedCapabilities: [
      "communication",
      "media",
      "research",
    ],
    preferredCapabilities: [
      "storytelling",
      "analysis",
      "initiative",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Moon",
      "Rahu",
    ],
    expectedEvidence: [
      "Communication",
      "Media",
      "Research",
    ],
    expectedThemes: [
      "Information",
      "Writing",
      "Public",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_writer",
    category: "profession",
    question: "Should I become a writer?",
    expectedCapabilities: [
      "communication",
      "storytelling",
      "creativity",
    ],
    preferredCapabilities: [
      "research",
      "learning",
      "media",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Moon",
      "Venus",
    ],
    expectedEvidence: [
      "Writing",
      "Communication",
      "Creative",
    ],
    expectedThemes: [
      "Expression",
      "Language",
      "Creativity",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_salesperson",
    category: "profession",
    question: "Should I work in sales?",
    expectedCapabilities: [
      "communication",
      "negotiation",
      "sales",
    ],
    preferredCapabilities: [
      "commerce",
      "customer_understanding",
      "initiative",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Venus",
      "Rahu",
    ],
    expectedEvidence: [
      "Sales",
      "Negotiation",
      "Commercial",
    ],
    expectedThemes: [
      "Persuasion",
      "Communication",
      "Commerce",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_architect",
    category: "profession",
    question: "Should I become an architect?",
    expectedCapabilities: [
      "creativity",
      "analysis",
      "execution",
    ],
    preferredCapabilities: [
      "strategic_thinking",
      "discipline",
      "innovation",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mars",
      "Mercury",
      "Venus",
    ],
    expectedEvidence: [
      "Design",
      "Technical",
      "Construction",
    ],
    expectedThemes: [
      "Structure",
      "Creativity",
      "Precision",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_designer",
    category: "profession",
    question: "Should I become a designer?",
    expectedCapabilities: [
      "creativity",
      "customer_understanding",
      "communication",
    ],
    preferredCapabilities: [
      "storytelling",
      "innovation",
      "media",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Venus",
      "Mercury",
    ],
    expectedEvidence: [
      "Design",
      "Creativity",
      "Aesthetic",
    ],
    expectedThemes: [
      "Beauty",
      "Expression",
      "Innovation",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_scientist",
    category: "profession",
    question: "Should I become a scientist?",
    expectedCapabilities: [
      "research",
      "analysis",
      "learning",
    ],
    preferredCapabilities: [
      "innovation",
      "discipline",
      "knowledge",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mercury",
      "Ketu",
      "Saturn",
      "Mars",
    ],
    expectedEvidence: [
      "Research",
      "Analysis",
      "Technical",
    ],
    expectedThemes: [
      "Investigation",
      "Systems",
      "Precision",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_military_officer",
    category: "profession",
    question: "Should I become a military officer?",
    expectedCapabilities: [
      "leadership",
      "execution",
      "discipline",
    ],
    preferredCapabilities: [
      "authority",
      "strategic_thinking",
      "responsibility",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Mars",
      "Sun",
      "Saturn",
    ],
    expectedEvidence: [
      "Courage",
      "Discipline",
      "Leadership",
    ],
    expectedThemes: [
      "Authority",
      "Action",
      "Responsibility",
    ],
    minimumConfidence: 55,
  },
  {
    id: "profession_spiritual_teacher",
    category: "profession",
    question: "Should I become a spiritual teacher?",
    expectedCapabilities: [
      "teaching",
      "mysticism",
      "dharma",
    ],
    preferredCapabilities: [
      "knowledge",
      "communication",
      "mentoring",
    ],
    forbiddenCapabilities: [],
    expectedPlanets: [
      "Jupiter",
      "Ketu",
      "Mercury",
    ],
    expectedEvidence: [
      "Spiritual",
      "Teaching",
      "Guidance",
    ],
    expectedThemes: [
      "Wisdom",
      "Dharma",
      "Spirituality",
    ],
    minimumConfidence: 55,
  },
];