import {
  NextRequest,
  NextResponse,
} from "next/server";

import { createClient } from "@/lib/supabase/server";

import {
  buildDataEngine,
  type BirthInput,
} from "@/server/dataEngine/buildDataEngine";

type DailyGuidanceRequest = {
  birth?: Partial<BirthInput>;
  selectedDateISO?: string;
  currentPlace?: {
  name?: string;
  lat: number;
  lon: number;
  timezone: string;
};
};

function isValidBirthInput(
  birth: Partial<BirthInput> | undefined
): birth is BirthInput {
  if (!birth) {
    return false;
  }

  return (
    typeof birth.dateISO === "string" &&
    birth.dateISO.trim().length > 0 &&
    typeof birth.time === "string" &&
    birth.time.trim().length > 0 &&
    typeof birth.timezone === "string" &&
    birth.timezone.trim().length > 0 &&
    typeof birth.lat === "number" &&
    Number.isFinite(birth.lat) &&
    typeof birth.lon === "number" &&
    Number.isFinite(birth.lon)
  );
}

export async function POST(
  request: NextRequest
) {
  try {
    /*
     * Authentication is enforced at the
     * API level as well as on the page.
     *
     * This prevents unauthenticated callers
     * from invoking the Data Engine directly.
     */
    const supabase =
      await createClient();

    const {
      data: { user },
      error: authError,
    } =
      await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Authentication required.",
        },
        {
          status: 401,
        }
      );
    }

    const body =
      (await request.json()) as DailyGuidanceRequest;

    if (!isValidBirthInput(body.birth)) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Valid birth details are required.",
        },
        {
          status: 400,
        }

      );
    }
const currentPlace = body.currentPlace;

if (
  !currentPlace ||
  typeof currentPlace.lat !== "number" ||
  !Number.isFinite(currentPlace.lat) ||
  currentPlace.lat < -90 ||
  currentPlace.lat > 90 ||
  typeof currentPlace.lon !== "number" ||
  !Number.isFinite(currentPlace.lon) ||
  currentPlace.lon < -180 ||
  currentPlace.lon > 180 ||
  typeof currentPlace.timezone !== "string" ||
  !currentPlace.timezone.trim()
) {
  return NextResponse.json(
    {
      ok: false,
      error: "Please select your present city.",
    },
    { status: 400 }
  );
}
    // Daily Guidance is restricted to today's date.
// Use the selected birth profile's timezone,
// not the server's timezone or the browser's date.

let selectedDateISO: string;

try {
  const formatter = new Intl.DateTimeFormat("en-CA", {
    timeZone: currentPlace.timezone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });

  const parts = formatter.formatToParts(new Date());

  const getPart = (type: string) =>
    parts.find((part) => part.type === type)?.value;

  selectedDateISO = [
    getPart("year"),
    getPart("month"),
    getPart("day"),
  ].join("-");
} catch {
  return NextResponse.json(
    {
      ok: false,
      error: "Invalid birth profile timezone.",
    },
    { status: 400 }
  );
}

    const result =
      await buildDataEngine({
        birth: {
          name:
            body.birth.name?.trim() ||
            undefined,

          dateISO:
            body.birth.dateISO.trim(),

          time:
            body.birth.time.trim(),

          timezone:
            body.birth.timezone.trim(),

          lat:
            body.birth.lat,

          lon:
            body.birth.lon,
        },

        currentPlace: {
  name: currentPlace.name?.trim() || undefined,
  lat: currentPlace.lat,
  lon: currentPlace.lon,
  timezone: currentPlace.timezone.trim(),
},

selectedDateISO,

        /*
         * Daily Guidance does not need
         * Pro-only Data Engine presentation
         * features.
         *
         * The prediction engine can still
         * internally use the active Dasha
         * information generated by
         * buildDataEngine.
         */
        plan: "light",
      });
const prediction = result.prediction.personalizedDaily;

const daily = prediction.dailyComparison;

const focus = daily?.dailyAreas[0] ?? null;
    return NextResponse.json({
  ok: true,

  date: result.meta.selectedDateISO,

  name: result.foundations.birthMeta?.name ?? null,

  prediction,

dailyFocus: focus
  ? {
      area: focus.area,
      importance: focus.strongestImportance,
      dashaScore: focus.dashaScore,
      moonSign: daily?.moonSign ?? null,
      moonNakshatra: daily?.moonNakshatra ?? null,
      signals: focus.signals,
      alignment:
        prediction.primaryTheme?.area === focus.area
          ? "aligned"
          : "different",
    }
  : null,

  snapshot: {
    ascendant: result.foundations.ascendant,

    natal: {
      ascendant: result.foundations.natal?.ascendant ?? null,
      planets: result.foundations.natal?.planets ?? [],
      ayanamsa: result.foundations.natal?.ayanamsa ?? "Lahiri",
    },

    dasha: {
  current: result.timing.dasha?.current ?? null,
  stack: result.timing.dasha?.stack ?? null,
  activeForPrediction:
    result.timing.dasha?.activeForPrediction ?? null,
},

    transits: {
      planets: result.transits.transitNow?.planets ?? [],
      moonToday: result.transits.transitNow?.moonToday ?? null,
    },
  },
});
  } catch (error) {
    console.error(
      "[daily-guidance] failed",
      error
    );

    return NextResponse.json(
      {
        ok: false,
        error:
          "Unable to generate daily guidance.",
      },
      {
        status: 500,
      }
    );
  }
}
